"""
Upgrade flow — the user-facing pages and form handlers for moving from a
free scan to a paid tier.

Routes:
  GET  /upgrade?scan={scan_id}       Choose between Tier 2 (R99) and Tier 3 (R450+)
  GET  /upgrade/return?scan={scan_id} Where PayFast redirects after success
  GET  /upgrade/cancel?scan={scan_id} Where PayFast redirects on cancel/abort
  POST /upgrade/rewrite               Tier 3 intake form submission (post-payment)

The actual PayFast checkout URL is generated by /api/payment/checkout/{tier}
in app.routes.payment. This module handles the surrounding UX.
"""

import uuid

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from app.db import get_scan, get_rewrite_intake, save_rewrite_intake
from app.templating import templates

router = APIRouter()


@router.get("/upgrade", response_class=HTMLResponse)
async def upgrade_page(request: Request, scan: str):
    """
    Tier 2/3 selection page.

    User just completed a free scan and clicked "get the full report" or
    "book a rewrite". They land here, see what each tier delivers, and pick
    one. Clicking a tier triggers the PayFast checkout flow via JavaScript.
    """
    scan_record = await get_scan(scan)
    if not scan_record:
        # Scan ID not found — invalid link, expired (>30 days), or fraud.
        # Send them back to the scan form rather than a hard error.
        return templates.TemplateResponse(
            request=request,
            name="upgrade_not_found.html",
            status_code=404,
        )

    # If they've already paid for Tier 2 or 3, route them to the right place
    if scan_record["tier"] >= 3:
        rewrite = await get_rewrite_intake(scan)
        if rewrite:
            # Already submitted intake — show status page
            return RedirectResponse(url=f"/upgrade/return?scan={scan}", status_code=303)
        # Paid for rewrite but not yet submitted intake — show intake form
        return templates.TemplateResponse(
            request=request,
            name="upgrade_rewrite.html",
            context={
                "scan_id": scan,
                "score": scan_record["score"],
                "email": scan_record["email"],
            },
        )

    if scan_record["tier"] == 2:
        # Already paid for Tier 2 — show the unlocked detailed report
        return RedirectResponse(url=f"/upgrade/report?scan={scan}", status_code=303)

    # Tier 1 — show the upsell page
    full_result = scan_record.get("full_result", {})
    return templates.TemplateResponse(
        request=request,
        name="upgrade.html",
        context={
            "scan_id": scan,
            "score": scan_record["score"],
            "region": scan_record["region"],
            "email": scan_record["email"],
            "full_result": full_result,
        },
    )


@router.get("/upgrade/return", response_class=HTMLResponse)
async def upgrade_return(request: Request, scan: str):
    """
    PayFast redirects the user here after a successful payment.

    Important: the ITN webhook (which actually unlocks the tier) may arrive
    BEFORE or AFTER this redirect. We handle both cases gracefully:
    - If the ITN got there first, scan.tier is already >= 2 — show success
    - If we got here first, show "processing" and let the page poll for status
    """
    scan_record = await get_scan(scan)
    if not scan_record:
        raise HTTPException(status_code=404, detail="Scan not found.")

    return templates.TemplateResponse(
        request=request,
        name="upgrade_return.html",
        context={
            "scan_id": scan,
            "score": scan_record["score"],
            "tier": scan_record["tier"],
            "email": scan_record["email"],
        },
    )


@router.get("/upgrade/cancel", response_class=HTMLResponse)
async def upgrade_cancel(request: Request, scan: str):
    """
    PayFast redirects here if the user cancels/abandons checkout.

    No tier change happens — they're still on Tier 1 with their free results.
    Soft landing: tell them no charge was made, offer to try again, link back
    to their free results.
    """
    scan_record = await get_scan(scan)
    return templates.TemplateResponse(
        request=request,
        name="upgrade_cancel.html",
        context={
            "scan_id": scan,
            "score": scan_record["score"] if scan_record else None,
        },
    )


@router.get("/upgrade/report", response_class=HTMLResponse)
async def upgrade_report(request: Request, scan: str):
    """
    Tier 2 unlocked detailed report.

    Only accessible if the scan's tier is >= 2 (i.e. payment confirmed via ITN).
    Otherwise redirects to the upsell page.
    """
    scan_record = await get_scan(scan)
    if not scan_record:
        raise HTTPException(status_code=404, detail="Scan not found.")

    if scan_record["tier"] < 2:
        # Not paid yet — bounce back to the upsell
        return RedirectResponse(url=f"/upgrade?scan={scan}", status_code=303)

    return templates.TemplateResponse(
        request=request,
        name="upgrade_unlocked.html",
        context={
            "scan_id": scan,
            "scan": scan_record,
            "result": scan_record.get("full_result", {}),
        },
    )


@router.post("/upgrade/rewrite")
async def submit_rewrite_intake(
    scan_id: str = Form(...),
    target_role: str = Form(...),
    target_industry: str = Form(""),
    years_experience: str = Form(...),
    key_achievements: str = Form(...),
    preferred_style: str = Form("modern"),
    additional_notes: str = Form(""),
    phone: str = Form(""),
):
    """
    Handle Tier 3 rewrite intake form submission.

    User has already paid (tier >= 3 enforced). They submit this form so the
    rewrite team has all the context they need. We store it and email the
    user a confirmation.
    """
    scan = await get_scan(scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found.")

    if scan["tier"] < 3:
        raise HTTPException(
            status_code=403,
            detail=(
                "This scan hasn't paid for the rewrite tier yet. If you've "
                "just paid, give it a minute for the payment confirmation and "
                "refresh the page."
            ),
        )

    # Reject duplicate submissions
    existing = await get_rewrite_intake(scan_id)
    if existing:
        raise HTTPException(
            status_code=409,
            detail="A rewrite intake has already been submitted for this scan.",
        )

    intake_id = str(uuid.uuid4())
    await save_rewrite_intake(
        intake_id=intake_id,
        scan_id=scan_id,
        target_role=target_role,
        target_industry=target_industry,
        years_experience=years_experience,
        key_achievements=key_achievements,
        preferred_style=preferred_style,
        additional_notes=additional_notes,
        phone=phone,
    )

    return {"status": "ok", "intake_id": intake_id}
