"""
Upgrade flow — the user-facing pages and form handlers for moving from a
free scan to a paid tier.

Routes:
  GET  /upgrade?scan={scan_id}       Choose between Tier 2 (R99) and Tier 3 (R450+)
  GET  /upgrade/return?scan={scan_id} Where PayFast redirects after success
  GET  /upgrade/cancel?scan={scan_id} Where PayFast redirects on cancel/abort
  POST /upgrade/rewrite               Tier 3 intake form submission (post-payment)

The actual PayFast checkout URL is generated by /api/payment/checkout/{tier}
in app.routes.payment. This module handles the surrounding UX.
"""

import uuid

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, RedirectResponse

from app.db import get_scan, get_rewrite_intake, save_rewrite_intake
from app.templating import templates

router = APIRouter()


@router.get("/upgrade", response_class=HTMLResponse)
async def upgrade_page(request: Request, scan: str):
    """
    Tier 2/3 selection page.

    User just completed a free scan and clicked "get the full report" or
    "book a rewrite". They land here, see what each tier delivers, and pick
    one. Clicking a tier triggers the PayFast checkout flow via JavaScript.
    """
    scan_record = await get_scan(scan)
    if not scan_record:
        # Scan ID not found — invalid link, expired (>30 days), or fraud.
        # Send them back to the scan form rather than a hard error.
        return templates.TemplateResponse(
            request=request,
            name="upgrade_not_found.html",
            status_code=404,
        )

    # If they've already paid for Tier 2 or 3, route them to the right place
    if scan_record["tier"] >= 3:
        rewrite = await get_rewrite_intake(scan)
        if rewrite:
            # Already submitted intake — show status page
            return RedirectResponse(url=f"/upgrade/return?scan={scan}", status_code=303)
        # Paid for rewrite but not yet submitted intake — show intake form
        return templates.TemplateResponse(
            request=request,
            name="upgrade_rewrite.html",
            context={
                "scan_id": scan,
                "score": scan_record["score"],
                "email": scan_record["email"],
            },
        )

    if scan_record["tier"] == 2:
        # Already paid for Tier 2 — show the unlocked detailed report
        return RedirectResponse(url=f"/upgrade/report?scan={scan}", status_code=303)

    # Tier 1 — show the upsell page
    full_result = scan_record.get("full_result", {})
    return templates.TemplateResponse(
        request=request,
        name="upgrade.html",
        context={
            "scan_id": scan,
            "score": scan_record["score"],
            "region": scan_record["region"],
            "email": scan_record["email"],
            "full_result": full_result,
        },
    )


@router.get("/upgrade/return", response_class=HTMLResponse)
async def upgrade_return(request: Request, scan: str):
    """
    PayFast redirects the user here after a successful payment.

    Important: the ITN webhook (which actually unlocks the tier) may arrive
    BEFORE or AFTER this redirect. We handle both cases gracefully:
    - If the ITN got there first, scan.tier is already >= 2 — show success
    - If we got here first, show "processing" and let the page poll for status
    """
    scan_record = await get_scan(scan)
    if not scan_record:
        raise HTTPException(status_code=404, detail="Scan not found.")

    return templates.TemplateResponse(
        request=request,
        name="upgrade_return.html",
        context={
            "scan_id": scan,
            "score": scan_record["score"],
            "tier": scan_record["tier"],
            "email": scan_record["email"],
        },
    )


@router.get("/upgrade/cancel", response_class=HTMLResponse)
async def upgrade_cancel(request: Request, scan: str):
    """
    PayFast redirects here if the user cancels/abandons checkout.

    No tier change happens — they're still on Tier 1 with their free results.
    Soft landing: tell them no charge was made, offer to try again, link back
    to their free results.
    """
    scan_record = await get_scan(scan)
    return templates.TemplateResponse(
        request=request,
        name="upgrade_cancel.html",
        context={
            "scan_id": scan,
            "score": scan_record["score"] if scan_record else None,
        },
    )


@router.get("/upgrade/report", response_class=HTMLResponse)
async def upgrade_report(request: Request, scan: str):
    """
    Tier 2 unlocked detailed report.

    Only accessible if the scan's tier is >= 2 (i.e. payment confirmed via ITN).
    Otherwise redirects to the upsell page.
    """
    scan_record = await get_scan(scan)
    if not scan_record:
        raise HTTPException(status_code=404, detail="Scan not found.")

    if scan_record["tier"] < 2:
        # Not paid yet — bounce back to the upsell
        return RedirectResponse(url=f"/upgrade?scan={scan}", status_code=303)

    full_result = scan_record.get("full_result", {})

    # --- Sector benchmarking ---
    from app.benchmarks import format_benchmark_context
    from app.scoring.industry import detect_industry
    detected = detect_industry(scan_record.get("cv_text", ""))
    benchmark = format_benchmark_context(scan_record["score"], detected.code)

    # --- AI bullet rewrites ---
    from app.ai_rewrites import extract_and_rewrite_bullets
    rewrites = extract_and_rewrite_bullets(scan_record.get("cv_text", ""), max_rewrites=5)

    # --- Per-fix score projections ---
    issues_with_projection = []
    cumulative = 0
    for issue in full_result.get("structural_issues", []):
        penalty = issue.get("penalty", 0)
        cumulative += penalty
        projected = min(scan_record["score"] + cumulative, 96)
        issues_with_projection.append({
            **issue,
            "projected_score_after_fix": scan_record["score"] + penalty,
            "projected_score_after_all": projected,
        })

    return templates.TemplateResponse(
        request=request,
        name="upgrade_unlocked.html",
        context={
            "scan_id": scan,
            "scan": scan_record,
            "result": full_result,
            "benchmark": benchmark,
            "rewrites": [r.__dict__ for r in rewrites],
            "issues_with_projection": issues_with_projection,
        },
    )


@router.post("/upgrade/rewrite")
async def submit_rewrite_intake(
    scan_id: str = Form(...),
    target_role: str = Form(...),
    target_industry: str = Form(""),
    years_experience: str = Form(...),
    key_achievements: str = Form(...),
    preferred_style: str = Form("modern"),
    additional_notes: str = Form(""),
    phone: str = Form(""),
):
    """
    Handle Tier 3 rewrite intake form submission.

    User has already paid (tier >= 3 enforced). They submit this form so the
    rewrite team has all the context they need. We store it and email the
    user a confirmation.
    """
    scan = await get_scan(scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found.")

    if scan["tier"] < 3:
        raise HTTPException(
            status_code=403,
            detail=(
                "This scan hasn't paid for the rewrite tier yet. If you've "
                "just paid, give it a minute for the payment confirmation and "
                "refresh the page."
            ),
        )

    # Reject duplicate submissions
    existing = await get_rewrite_intake(scan_id)
    if existing:
        raise HTTPException(
            status_code=409,
            detail="A rewrite intake has already been submitted for this scan.",
        )

    intake_id = str(uuid.uuid4())
    await save_rewrite_intake(
        intake_id=intake_id,
        scan_id=scan_id,
        target_role=target_role,
        target_industry=target_industry,
        years_experience=years_experience,
        key_achievements=key_achievements,
        preferred_style=preferred_style,
        additional_notes=additional_notes,
        phone=phone,
    )

    return {"status": "ok", "intake_id": intake_id}


@router.get("/upgrade/report/pdf")
async def upgrade_report_pdf(scan: str):
    """
    Generate and return a PDF version of the Tier 2 diagnostic report.

    Only available for Tier 2+ scans. Uses reportlab to build a branded
    PDF the user can save, print, or share.
    """
    scan_record = await get_scan(scan)
    if not scan_record:
        raise HTTPException(status_code=404, detail="Scan not found.")

    if scan_record["tier"] < 2:
        raise HTTPException(status_code=403, detail="Report not unlocked.")

    full_result = scan_record.get("full_result", {})
    bd = full_result.get("score_breakdown", {})

    from app.benchmarks import format_benchmark_context
    from app.scoring.industry import detect_industry
    from app.ai_rewrites import extract_and_rewrite_bullets

    detected = detect_industry(scan_record.get("cv_text", ""))
    benchmark = format_benchmark_context(scan_record["score"], detected.code)
    rewrites = extract_and_rewrite_bullets(scan_record.get("cv_text", ""), max_rewrites=5)

    # --- Build PDF ---
    import io
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_LEFT, TA_CENTER
    from fastapi.responses import StreamingResponse

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=25*mm, rightMargin=25*mm,
                            topMargin=20*mm, bottomMargin=20*mm)

    oxblood = HexColor("#7A1F1F")
    ink = HexColor("#1A1A18")
    ink_muted = HexColor("#6B6B6B")

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("ReportTitle", fontName="Helvetica-Bold", fontSize=22,
                              textColor=oxblood, spaceAfter=6))
    styles.add(ParagraphStyle("SectionHead", fontName="Helvetica-Bold", fontSize=14,
                              textColor=ink, spaceBefore=18, spaceAfter=8))
    styles.add(ParagraphStyle("SubHead", fontName="Helvetica-Bold", fontSize=11,
                              textColor=ink, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle("Body", fontName="Helvetica", fontSize=10,
                              textColor=ink, leading=14, spaceAfter=6))
    styles.add(ParagraphStyle("Small", fontName="Helvetica", fontSize=8,
                              textColor=ink_muted, leading=10))
    styles.add(ParagraphStyle("Score", fontName="Helvetica-Bold", fontSize=36,
                              textColor=oxblood, alignment=TA_CENTER))

    story = []

    # Header
    story.append(Paragraph("Cited.", styles["ReportTitle"]))
    story.append(Paragraph("Full Diagnostic Report", styles["SectionHead"]))
    story.append(Paragraph(f"Scan ID: {scan} &nbsp;|&nbsp; Region: {scan_record['region']} &nbsp;|&nbsp; "
                           f"Email: {scan_record.get('email', 'N/A')}", styles["Small"]))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=ink))
    story.append(Spacer(1, 10))

    # Score
    story.append(Paragraph(f"{scan_record['score']} / 100", styles["Score"]))
    story.append(Spacer(1, 6))

    # Score breakdown table
    score_data = [
        ["Parseability", "Structure", "Keywords", "Content"],
        [f"{bd.get('parseability',0)}/{bd.get('parseability_max',40)}",
         f"{bd.get('structure',0)}/{bd.get('structure_max',20)}",
         f"{bd.get('keywords',0)}/{bd.get('keywords_max',25)}",
         f"{bd.get('content',0)}/{bd.get('content_max',15)}"],
    ]
    t = Table(score_data, colWidths=[doc.width/4]*4)
    t.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 0.5, ink_muted),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))

    # Benchmark
    story.append(Paragraph("Sector Benchmark", styles["SectionHead"]))
    story.append(Paragraph(benchmark["position_description"], styles["Body"]))

    # Issues
    story.append(Paragraph("All Issues Detected", styles["SectionHead"]))
    for issue in full_result.get("structural_issues", []):
        sev = issue.get("severity", "").upper()
        penalty = issue.get("penalty", 0)
        desc = issue.get("description", "")
        itype = issue.get("type", "").replace("_", " ").title()
        story.append(Paragraph(
            f"<b>{itype}</b> &nbsp;[{sev} · −{penalty} pts] — {desc}",
            styles["Body"],
        ))

    # Keywords
    story.append(Paragraph("Keyword Analysis", styles["SectionHead"]))
    matched = bd.get("matched_keywords", [])
    missing = full_result.get("missing_keywords", [])
    if matched:
        story.append(Paragraph(f"<b>Matched ({len(matched)}):</b> {', '.join(matched)}", styles["Body"]))
    if missing:
        story.append(Paragraph(f"<b>Missing ({len(missing)}):</b> {', '.join(missing)}", styles["Body"]))

    # AI Rewrites
    if rewrites:
        story.append(Paragraph("Bullet Point Improvements", styles["SectionHead"]))
        for i, r in enumerate(rewrites, 1):
            story.append(Paragraph(f"<b>Bullet {i} — Original:</b>", styles["SubHead"]))
            story.append(Paragraph(f"<i>{r.original[:200]}</i>", styles["Body"]))
            story.append(Paragraph(f"<b>Suggested:</b>", styles["SubHead"]))
            story.append(Paragraph(r.suggestion[:250], styles["Body"]))
            story.append(Paragraph(f"<b>Why:</b> {r.improvement_note}", styles["Small"]))
            story.append(Spacer(1, 6))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=ink_muted))
    story.append(Paragraph(
        "Generated by Cited · cited.co.za · This report is available online for 30 days.",
        styles["Small"],
    ))

    doc.build(story)
    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=cited-report-{scan[:8]}.pdf"},
    )
